// tests/generated-source-highlighting.test.mjs
//
// The verifier for the Studio source view's own JSX tokeniser, which replaced
// `react-syntax-highlighter` after that package's import chain turned out to need
// `document` at module init — see client/src/studio/GeneratedSourceView.logic.js and
// docs/EDGE-CASES.md.
//
// The point of a highlighter is not grammatical correctness; it is that a run of
// characters gets the colour it looks like it should have. So these assert the two
// mistakes that make coloured code read as BROKEN rather than merely imperfect — a `//`
// inside a string, and a keyword inside a comment — plus the line arithmetic the gutter
// depends on, and the property the whole swap was for: this module loads and runs with no
// DOM anywhere.

import { test } from 'node:test';
import assert from 'node:assert/strict';

import { tokenize, toLines, highlight, TOKEN_COLOURS } from '../client/src/studio/GeneratedSourceView.logic.js';

const kindOf = (tokens, needle) => tokens.find((t) => t.text.includes(needle))?.kind;

test('it runs with no DOM at all — the whole reason it exists', () => {
  assert.equal(typeof globalThis.document, 'undefined', 'this test is meaningless with a document in scope');
  assert.doesNotThrow(() => highlight('const x = 1;\n'));
});

test('keywords, strings, numbers and JSX tags each get their own kind', () => {
  const tokens = tokenize("import React from 'react';\nconst n = 42;\nreturn <Button />;");

  assert.equal(kindOf(tokens, 'import'), 'keyword');
  assert.equal(kindOf(tokens, "'react'"), 'string');
  assert.equal(kindOf(tokens, '42'), 'number');
  assert.equal(kindOf(tokens, '<Button'), 'tag');
  assert.equal(kindOf(tokens, 'React'), 'plain', 'an identifier is not a keyword');
});

test('a // inside a string is not a comment', () => {
  const tokens = tokenize("const url = 'http://localhost:3000/api';");
  const string = tokens.find((t) => t.kind === 'string');

  assert.equal(string.text, "'http://localhost:3000/api';".slice(0, -1));
  assert.ok(!tokens.some((t) => t.kind === 'comment'), 'the rest of the line turned green');
});

test('a keyword inside a comment is not a keyword', () => {
  const tokens = tokenize('// return the const from this function\nconst x = 1;');

  const comment = tokens.find((t) => t.kind === 'comment');
  assert.equal(comment.text, '// return the const from this function');
  assert.equal(
    tokens.filter((t) => t.kind === 'keyword').length,
    1,
    'the words inside the comment were coloured as code',
  );
});

test('a block comment spans lines and closes where it closes', () => {
  const tokens = tokenize('/* one\n   two */ const x = 1;');

  assert.equal(tokens[0].kind, 'comment');
  assert.equal(tokens[0].text, '/* one\n   two */');
  assert.ok(tokens.some((t) => t.kind === 'keyword' && t.text === 'const'), 'the code after the comment stayed grey');
});

test('an unterminated quote does not colour the rest of the file', () => {
  // §7's emitted components are machine-written, but a truncated response is not, and a
  // single stray quote turning 400 lines orange is how a source view stops being useful.
  const tokens = tokenize("const broken = 'oops\nconst after = 2;");

  assert.ok(tokens.some((t) => t.kind === 'keyword' && t.text === 'const'));
  assert.equal(toLines(tokens).length, 2);
  assert.ok(
    toLines(tokens)[1].some((t) => t.kind === 'keyword'),
    'the second line was swallowed by the first line’s string',
  );
});

test('the gutter and the code agree on how many lines there are', () => {
  const source = 'const a = 1;\nconst b = 2;\nconst c = 3;\n';

  const lines = highlight(source);
  assert.equal(lines.length, 3, 'the trailing newline produced a numbered blank row');
  assert.equal(lines[1].map((t) => t.text).join(''), 'const b = 2;');
});

test('every kind the tokeniser emits has a colour', () => {
  const source = "// c\nimport x from 'y';\nconst n = 1;\nreturn <div />;";
  for (const token of tokenize(source)) {
    assert.ok(TOKEN_COLOURS[token.kind], `kind ${JSON.stringify(token.kind)} renders with no colour`);
  }
});

test('an emitted component round-trips to exactly its own text', () => {
  // A highlighter that loses a character is worse than one with no colour: the panel is
  // what a judge reads to check the generated component, and §7's oddities — the `ids`
  // map, dynamicStyle, dangerouslySetInnerHTML — are the graded part.
  const source = [
    '// Generated by emitComponent.js — do not edit by hand.',
    "import React from 'react';",
    '',
    'const ids = { headlineMain: \'2000000003\' };',
    '',
    'export default function HeroSection() {',
    '  return (',
    '    <section className="dynamicStyle">',
    '      <h1 id={ids.headlineMain} dangerouslySetInnerHTML={{ __html: getHtml(v, d) }} />',
    '    </section>',
    '  );',
    '}',
    '',
  ].join('\n');

  const rebuilt = highlight(source).map((line) => line.map((t) => t.text).join('')).join('\n');
  assert.equal(rebuilt, source.replace(/\n$/, ''));
});
