export function emitBlogMock(ir) {
  const elements = ir.elements || [];
  const pageName = ir.pageName || 'Blog';

  const idsMapLines = elements.map(el => `  ${el.elementName}: '${el.fieldId}',`).join('\n');
  
  const defaultsMapLines = elements.map(el => {
    let def = el.default || '';
    if (el.contentType === 'Image') def = el.default || 'default/images/hero-placeholder.jpg';
    return `  ['${el.fieldId}']: ${JSON.stringify(def)},`;
  }).join('\n');

  const cardNodes = [];
  for (let i = 1; i <= 9; i++) {
    cardNodes.push(`
          <motion.div variants={item} className="group flex flex-col bg-white rounded-3xl overflow-hidden shadow-sm hover:shadow-2xl hover:-translate-y-1 transition-all duration-500 border border-zinc-100">
             <div className="relative overflow-hidden aspect-video">
                <img 
                  id={ids.card_${i}_image}
                  className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105 dynamicStyle2"
                  src={getImage(data?.[ids.card_${i}_image] || DEFAULTS[ids.card_${i}_image])}
                  onError={errorImage}
                  alt="Blog image"
                />
                <div className="absolute top-4 right-4 bg-white/95 backdrop-blur-md px-4 py-1.5 rounded-full text-[11px] font-bold tracking-widest uppercase text-zinc-900 shadow-sm">
                   <span id={ids.card_${i}_tag} dangerouslySetInnerHTML={{ __html: getHtml(data, ids.card_${i}_tag, DEFAULTS[ids.card_${i}_tag]) }} className="dynamicStyle" />
                </div>
             </div>
             <div className="p-8 flex flex-col flex-grow">
                <h3 
                  id={ids.card_${i}_title} 
                  className="text-2xl font-bold text-zinc-900 mb-3 group-hover:text-blue-600 transition-colors dynamicStyle leading-tight"
                  dangerouslySetInnerHTML={{ __html: getHtml(data, ids.card_${i}_title, DEFAULTS[ids.card_${i}_title]) }}
                />
                <p 
                  id={ids.card_${i}_author} 
                  className="text-sm font-medium text-zinc-400 mb-5 uppercase tracking-wider dynamicStyle"
                  dangerouslySetInnerHTML={{ __html: getHtml(data, ids.card_${i}_author, DEFAULTS[ids.card_${i}_author]) }}
                />
                <p 
                  id={ids.card_${i}_excerpt} 
                  className="text-zinc-600 leading-relaxed dynamicStyle line-clamp-3"
                  dangerouslySetInnerHTML={{ __html: getHtml(data, ids.card_${i}_excerpt, DEFAULTS[ids.card_${i}_excerpt]) }}
                />
             </div>
          </motion.div>
    `);
  }

  return `// Generated by emitBlogMock.js — Beautiful Mock Wireframe

import React, { useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { fetchElementsByIds } from '../../redux/fetchElementsByIds.js';
import { getHtml } from '../../utils/getHtml.js';
import { getImage, errorImage } from '../../utils/image.js';
import { motion } from 'framer-motion';

export const ids = {
${idsMapLines}
};

export const DEFAULTS = {
${defaultsMapLines}
};

export function getAllMountFieldIds() {
  return Object.values(ids);
}

export default function BlogSection({ pageName = '${pageName}', section = {} }) {
  const dispatch = useDispatch();
  const data = useSelector((state) => state.cms.allSections[pageName] || {});
  const cssData = useSelector((state) => state.cms.allSectionsCss[pageName] || {});

  useEffect(() => {
    dispatch(fetchElementsByIds({ elementIds: getAllMountFieldIds(), pageName }));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [pageName]);

  useEffect(() => {
    Object.entries(cssData).forEach(([fieldId, cssText]) => {
      const node = document.getElementById(fieldId);
      if (node && cssText) node.style.cssText = cssText;
    });
  }, [cssData]);

  const container = {
    hidden: { opacity: 0 },
    show: {
      opacity: 1,
      transition: { staggerChildren: 0.1 }
    }
  };
  const item = {
    hidden: { opacity: 0, y: 30 },
    show: { opacity: 1, y: 0, transition: { duration: 0.6, ease: [0.22, 1, 0.36, 1] } }
  };

  return (
    <section className="bg-zinc-50 py-24 min-h-screen relative overflow-hidden font-sans">
      <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-20 pointer-events-none mix-blend-overlay"></div>
      
      <div className="max-w-7xl mx-auto px-6 relative z-10">
        <motion.h1 
          id={ids.blog_title}
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, ease: "easeOut" }}
          className="text-5xl md:text-7xl font-extrabold tracking-tight text-zinc-900 text-center mb-20 dynamicStyle"
          dangerouslySetInnerHTML={{ __html: getHtml(data, ids.blog_title, DEFAULTS[ids.blog_title]) }}
        />

        <motion.div 
          variants={container} 
          initial="hidden" 
          whileInView="show" 
          viewport={{ once: true, margin: "-100px" }}
          className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-10"
        >
${[...cardNodes].join('\n')}
        </motion.div>

        <motion.div 
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          className="mt-20 flex justify-center"
        >
           <div 
             id={ids.blog_pagination} 
             className="px-8 py-3 bg-white border border-zinc-200 rounded-full text-sm font-bold text-zinc-900 uppercase tracking-widest cursor-pointer hover:bg-zinc-100 hover:scale-105 transition-all duration-300 shadow-sm dynamicStyle"
             dangerouslySetInnerHTML={{ __html: getHtml(data, ids.blog_pagination, DEFAULTS[ids.blog_pagination]) }}
           />
        </motion.div>
      </div>
    </section>
  );
}
`;
}
